const sampleData = {
	products: [
		{
			name: "Polo スポーツストレッチシャツ",
			slug: "polo-sporting-stretch-shirt",
			category: "Men's Dress Shirts",
			description: "モダンコンフォートなクラシックポロシャツ",
			images: [
				"/images/sample-products/p1-1.jpg",
				"/images/sample-products/p1-2.jpg",
			],
			price: 6200,
			brand: "Polo",
			rating: 4.5,
			numReviews: 10,
			stock: 5,
			isFeatured: true,
			banner: "banner-1.jpg",
		},
		{
			name: "Brooks Brothers ロングスリーブシャツ",
			slug: "brooks-brothers-long-sleeved-shirt",
			category: "Men's Dress Shirts",
			description: "プレミアムなコンフォートシャツ",
			images: [
				"/images/sample-products/p2-1.jpg",
				"/images/sample-products/p2-2.jpg",
			],
			price: 12000,
			brand: "Brooks Brothers",
			rating: 4.2,
			numReviews: 8,
			stock: 10,
			isFeatured: true,
			banner: "banner-2.jpg",
		},
		{
			name: "Tommy Hilfiger クラシックフィットドレスシャツ",
			slug: "tommy-hilfiger-classic-fit-dress-shirt",
			category: "Men's Dress Shirts",
			description: "sophistication と comfortの完全なブレンド",
			images: [
				"/images/sample-products/p3-1.jpg",
				"/images/sample-products/p3-2.jpg",
			],
			price: 15800.0,
			brand: "Tommy Hilfiger",
			rating: 4.9,
			numReviews: 3,
			stock: 0,
			isFeatured: false,
			banner: null,
		},
		{
			name: "Calvin Klein スリムフィットストレッチシャツ",
			slug: "calvin-klein-slim-fit-stretch-shirt",
			category: "Men's Dress Shirts",
			description: "ストレッチファブリックなスタイル",
			images: [
				"/images/sample-products/p4-1.jpg",
				"/images/sample-products/p4-2.jpg",
			],
			price: 7800,
			brand: "Calvin Klein",
			rating: 3.6,
			numReviews: 5,
			stock: 10,
			isFeatured: false,
			banner: null,
		},
		{
			name: "Polo Ralph Lauren オックスフォードシャツ",
			slug: "polo-ralph-lauren-oxford-shirt",
			category: "Men's Dress Shirts",
			description: "オックスフォードファブリックなポロの象徴的なシャツ",
			images: [
				"/images/sample-products/p5-1.jpg",
				"/images/sample-products/p5-2.jpg",
			],
			price: 13200,
			brand: "Polo",
			rating: 4.7,
			numReviews: 18,
			stock: 6,
			isFeatured: false,
			banner: null,
		},
		{
			name: "Polo Classic ピンクフーディ",
			slug: "polo-classic-pink-hoodie",
			category: "Men's Sweatshirts",
			description: "ソフトでスタイリッシュで完全なフーディ",
			images: [
				"/images/sample-products/p6-1.jpg",
				"/images/sample-products/p6-2.jpg",
			],
			price: 15200,
			brand: "Polo",
			rating: 4.6,
			numReviews: 12,
			stock: 8,
			isFeatured: true,
			banner: null,
		},
	],
};

export default sampleData;
